fixtures:
  repositories:
    stdlib:  "git://github.com/puppetlabs/puppetlabs-stdlib.git"
    concat:  "git://github.com/puppetlabs/puppet-concat.git"
    postgresql:    "git://github.com/puppetlabs/puppetlabs-postgresql.git"
